### ISSUE TITLE
Firebase Tips

### ISSUE THREAD

**Issue by bxute** [Peter-Wanden/TheKitchenMenu#1]
### Some tips on Firebase Database storage
 - Firebase database works on key/value pairs
 - It has nested nodes
 - Each node can have multiple key/value pairs.

Lets suppose you want to store Products Info.
Product id: 0
Product name: product_one
Product Description: product_desc

You can create a node like this:
![capture](https://user-images.githubusercontent.com/10809719/43354081-f89a1d2a-9262-11e8-8b56-550da5c2cc96.PNG)

----

First, try to create a structure in terms of nodes and key/value pairs.
Then let me know how you have done it.

Can you send me your database structure drawn on a paper. ?

**Comment by Peter-Wanden** [comment]
Hi Ankit, 

Please find my relational database schema attached. As you'll see its a little too complex to translate into a firebase database for a first try. So I was thinking of just the product table for now as that would be most useful for users, then at a later date recipes and their ingredients. Also using Firestore for recipe and product images.

![image](https://user-images.githubusercontent.com/18653520/43354610-7586cf20-9247-11e8-9b17-6546af355b53.png)

**Comment by bxute** [comment]
Ok Peter, I will take some time to arrange them all.

**Comment by bxute** [comment]
![fireshot capture 1 - udacitytest database firebase cons_ - https___console firebase google com](https://user-images.githubusercontent.com/10809719/43504845-75899a3c-9582-11e8-9b7f-5948a16a1c69.png)

**Comment by bxute** [comment]
This should be your node structure.
**Note:**
 - You cannot establish any kind of relations here.
All these relations should be handled from client side only or server side.

You have to make key/value entries in the database.

**Comment by Peter-Wanden** [comment]
Thank you for your detailed response. This looks great. I have since implemented the product table and it works across devices. If I add a product it shows up on every device that has the app installed. Result! :)
